# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-29 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='login_token',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
