# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_player_login_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='name',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
