# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 08:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_player_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerMenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=64)),
                ('url', models.CharField(max_length=128)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Player')),
            ],
        ),
    ]
