# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-29 23:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='channel',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='chat.Channel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='team.Player'),
        ),
    ]
