# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 13:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_squashed_0005_auto_20170718_1026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channel',
            options={'permissions': (('channel.admin', 'View all channels, send without delay'),)},
        ),
        migrations.AlterField(
            model_name='message',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chat.Channel'),
        ),
        migrations.AlterField(
            model_name='message',
            name='posted',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='message',
            name='visible',
            field=models.DateTimeField(),
        ),
    ]
