# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-16 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20170630_0151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['posted']},
        ),
        migrations.AddField(
            model_name='message',
            name='posted',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='visible',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
