# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-29 23:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('token', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name=6)),
                ('mined_time', models.DateField(default=None, null=True)),
                ('sold_at', models.DateField(default=None, null=True)),
                ('sold_for', models.IntegerField(default=None, null=True)),
                ('owner', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='team.Team')),
            ],
            options={
                'permissions': (('insert_token', 'Insert tokens'), ('sell', 'Sell goods')),
            },
        ),
        migrations.CreateModel(
            name='GoodsType',
            fields=[
                ('type_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='goods',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsType'),
        ),
    ]
