# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-29 23:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20170630_0117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'permissions': (('mine', 'Insert tokens'), ('sell', 'Sell goods')), 'verbose_name_plural': 'Goods'},
        ),
    ]
