# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 16:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_squashed_0005_player_instr'),
        ('goods', '0003_auto_20170718_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finish_after', models.DateTimeField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Player')),
                ('selling', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsType')),
            ],
        ),
    ]
