# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_sellslot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellslot',
            name='finish_after',
            field=models.DateTimeField(null=True),
        ),
    ]
