# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_auto_20170630_0346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodstype',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
