# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 16:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_auto_20170718_1845'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sellslot',
            options={'ordering': ['pk']},
        ),
    ]
