# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_auto_20170630_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='token',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
    ]
