# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 08:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_auto_20170718_1852'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellslot',
            old_name='finish_after',
            new_name='started_at',
        ),
    ]
