# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0008_auto_20170720_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='mined_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='goods',
            name='sold_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
