# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0009_auto_20170720_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='sold_for',
            field=models.FloatField(default=None, null=True),
        ),
    ]
