# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-24 09:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0010_auto_20170720_1050'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'permissions': (('can_mine', 'Insert tokens'), ('can_sell', 'Sell goods')), 'verbose_name_plural': 'Goods'},
        ),
    ]
